apiVersion: v1
kind: Secret
metadata:
  name: postal-converter-secret
  labels:
    app.kubernetes.io/name: postal-converter-ja
type: Opaque
stringData:
  POSTGRES_DATABASE_URL: postgres://postgres:postgres_password@postgres:5432/zip_code_db
  MYSQL_DATABASE_URL: mysql://mysql_user:u_password@mysql:3306/zip_code_db
  SQLITE_DATABASE_PATH: /data/postal_codes.sqlite3
  REDIS_URL: redis://redis:6379
