apiVersion: v1
kind: Service
metadata:
  name: postal-converter-api
  labels:
    app.kubernetes.io/name: postal-converter-ja
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postal-converter-ja
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: 3202
      targetPort: http
