secret:
  create: false

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: postal-converter-ja
  target:
    creationPolicy: Owner
  data:
    POSTGRES_DATABASE_URL:
      key: postal-converter-ja/database
      property: postgres_url
    MYSQL_DATABASE_URL:
      key: postal-converter-ja/database
      property: mysql_url
    SQLITE_DATABASE_PATH:
      key: postal-converter-ja/database
      property: sqlite_path
    REDIS_URL:
      key: postal-converter-ja/cache
      property: redis_url
