apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postal-converter-ja-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: postal-converter-ja
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/mt4110/postal_converter_ja.git
    targetRevision: main
    path: deploy/helm/postal-converter-ja
    helm:
      releaseName: postal-converter-ja
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postal-converter-ja-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postal-converter-ja-stg
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: postal-converter-ja
    env: stg
spec:
  project: default
  source:
    repoURL: https://github.com/mt4110/postal_converter_ja.git
    targetRevision: main
    path: deploy/helm/postal-converter-ja
    helm:
      releaseName: postal-converter-ja
      valueFiles:
        - values-stg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postal-converter-ja-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postal-converter-ja-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: postal-converter-ja
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/mt4110/postal_converter_ja.git
    targetRevision: main
    path: deploy/helm/postal-converter-ja
    helm:
      releaseName: postal-converter-ja
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postal-converter-ja-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
