{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postal-converter-ja.fullname" . }}
  labels:
    {{- include "postal-converter-ja.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postal-converter-ja.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  {{- if .Values.networkPolicy.ingress.from }}
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingress.from | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  {{- else }}
  ingress: []
  {{- end }}
{{- end }}
