apiVersion: v1
kind: Service
metadata:
  name: {{ include "postal-converter-ja.fullname" . }}
  labels:
    {{- include "postal-converter-ja.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "postal-converter-ja.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
